/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulários;

import livraria.CalcularValorTotal;
import livraria.Livraria;
import livraria.produtos.*;


/**
 *
 * @author 00715111213
 */
public class InterfaceLivraria extends javax.swing.JFrame {

    /**
     * Creates new form Livraria
     */
    public InterfaceLivraria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelRotulo = new javax.swing.JLabel();
        jLabelTipoProduto = new javax.swing.JLabel();
        jLabelValorProduto = new javax.swing.JLabel();
        jTextFieldValorProduto = new javax.swing.JTextField();
        jComboBoxTipoProduto = new javax.swing.JComboBox<>();
        jLabelValorASerPago = new javax.swing.JLabel();
        jTextFieldValorASerPago = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria CJ");

        jLabelRotulo.setText("Simulador de pagamento:");

        jLabelTipoProduto.setText("Tipo do produto:");

        jLabelValorProduto.setText("Valor do produto:");

        jComboBoxTipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Livro físico", "Livro digital", "Revista física", "Revista digital", "Jogo de tabuleiro", "Vídeo game físico", "Vídeo game digital" }));

        jLabelValorASerPago.setText("Valor a ser pago:");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelRotulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValorProduto)
                            .addComponent(jLabelTipoProduto)
                            .addComponent(jLabelValorASerPago))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValorProduto)
                            .addComponent(jComboBoxTipoProduto, 0, 161, Short.MAX_VALUE)
                            .addComponent(jTextFieldValorASerPago))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelRotulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorProduto)
                    .addComponent(jTextFieldValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoProduto)
                    .addComponent(jComboBoxTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorASerPago)
                    .addComponent(jTextFieldValorASerPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextFieldValorASerPago.setText("");
        jTextFieldValorProduto.setText("");
        jComboBoxTipoProduto.setSelectedItem("--");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JogosTabuleiro jogoTabuleiro = new JogosTabuleiro();
        LivrosDigitais livroDigital = new LivrosDigitais();
        LivrosFisicos livroFisico = new LivrosFisicos();
        RevistasDigitais revistaDigital = new RevistasDigitais();
        RevistasFisicas revistaFisica = new RevistasFisicas();
        VideoGamesDigitais videoGameDigital = new VideoGamesDigitais();
        VideoGamesFisicos videoGameFisico = new VideoGamesFisicos();
        
        String tipo = (String)jComboBoxTipoProduto.getSelectedItem();
        double valor = Double.parseDouble(jTextFieldValorProduto.getText());
        CalcularValorTotal calculo = new CalcularValorTotal();
        
        Livraria livraria = new Livraria(valor);

        if (tipo.equalsIgnoreCase("Jogo de tabuleiro")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, jogoTabuleiro)));
        }
        
        if (tipo.equalsIgnoreCase("Livro digital")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, livroDigital)));
        }
        
        if (tipo.equalsIgnoreCase("Livro físico")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, livroFisico)));
        }
        
        if (tipo.equalsIgnoreCase("Revista digital")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, revistaDigital)));
        }
        
        if (tipo.equalsIgnoreCase("Revista física")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, revistaFisica)));
        }
        
        if (tipo.equalsIgnoreCase("Vídeo game digital")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, videoGameDigital)));
        }
        
        if (tipo.equalsIgnoreCase("Vídeo game físico")){
            jTextFieldValorASerPago.setText(String.valueOf(calculo.calcularPreco(livraria, videoGameFisico)));
        }
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivraria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLivraria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxTipoProduto;
    private javax.swing.JLabel jLabelRotulo;
    private javax.swing.JLabel jLabelTipoProduto;
    private javax.swing.JLabel jLabelValorASerPago;
    private javax.swing.JLabel jLabelValorProduto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldValorASerPago;
    private javax.swing.JTextField jTextFieldValorProduto;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
